services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./hf_cache:/tmp/huggingface
    ports:
      - "8000:8000"
    command: python manage.py runserver_plus 0.0.0.0:8000 --cert mkcert/localhost.pem --key mkcert/localhost-key.pem
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: minio-container
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - "${MINIO_CERTS_PATH}:/root/.minio/certs"
      - "${MINIO_DATA_PATH}:/data"
    command: server /data --console-address ":9001"
