openapi: 3.0.3
info:
  title: Between IMS
  version: 1.0.0
  description: An Internship matching system for everyone
paths:
  /api/lightcast/skills/:
    get:
      operationId: api_lightcast_skills_retrieve
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/token/:
    post:
      operationId: api_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyTokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MyTokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MyTokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyTokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: api_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/user_account/departments/:
    get:
      operationId: api_user_account_departments_list
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Department'
          description: ''
  /api/user_account/programs/:
    get:
      operationId: api_user_account_programs_list
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProgramNested'
          description: ''
  /api/user_account/register/applicant/:
    post:
      operationId: api_user_account_register_applicant_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicantRegister'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ApplicantRegister'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ApplicantRegister'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicantRegister'
          description: ''
  /api/user_account/register/cea/:
    post:
      operationId: api_user_account_register_cea_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CareerEmplacementAdminRegister'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CareerEmplacementAdminRegister'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CareerEmplacementAdminRegister'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CareerEmplacementAdminRegister'
          description: ''
  /api/user_account/register/company/:
    post:
      operationId: api_user_account_register_company_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyRegister'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CompanyRegister'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CompanyRegister'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyRegister'
          description: ''
  /api/user_account/register/ojt_coordinator/:
    post:
      operationId: api_user_account_register_ojt_coordinator_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OJTCoordinatorRegister'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OJTCoordinatorRegister'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OJTCoordinatorRegister'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OJTCoordinatorRegister'
          description: ''
  /api/user_account/schools/:
    get:
      operationId: api_user_account_schools_list
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/School'
          description: ''
  /api/user_account/schools/departments/programs/:
    get:
      operationId: api_user_account_schools_departments_programs_list
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NestedSchoolDepartmentProgram'
          description: ''
components:
  schemas:
    ApplicantRegister:
      type: object
      properties:
        first_name:
          type: string
          maxLength: 100
        last_name:
          type: string
          maxLength: 100
        middle_initial:
          type: string
          writeOnly: true
          default: ''
        applicant_email:
          type: string
          format: email
          writeOnly: true
        school:
          type: string
          format: uuid
          nullable: true
        password:
          type: string
          writeOnly: true
        confirm_password:
          type: string
          writeOnly: true
        department:
          type: integer
          nullable: true
        program:
          type: integer
          nullable: true
        academic_program:
          type: string
          nullable: true
          maxLength: 100
        hard_skills:
          type: array
          items:
            type: string
        soft_skills:
          type: array
          items:
            type: string
        address:
          type: string
          maxLength: 255
        quick_introduction:
          type: string
          nullable: true
          maxLength: 500
        resume:
          type: string
          format: uri
        enrollment_record:
          type: string
          format: uri
          nullable: true
      required:
      - address
      - applicant_email
      - confirm_password
      - first_name
      - last_name
      - password
      - resume
    CareerEmplacementAdminRegister:
      type: object
      properties:
        CEA_email:
          type: string
          format: email
          writeOnly: true
        password:
          type: string
          writeOnly: true
        confirm_password:
          type: string
          writeOnly: true
        school:
          type: string
          format: uuid
      required:
      - CEA_email
      - confirm_password
      - password
      - school
    CompanyRegister:
      type: object
      properties:
        company_name:
          type: string
          maxLength: 255
        company_address:
          type: string
          maxLength: 255
        company_website_url:
          type: string
          nullable: true
          maxLength: 255
        company_email:
          type: string
          format: email
          writeOnly: true
        password:
          type: string
          writeOnly: true
        confirm_password:
          type: string
          writeOnly: true
        company_information:
          type: string
          maxLength: 1000
        business_nature:
          type: string
          maxLength: 100
        profile_picture:
          type: string
          format: uri
        background_image:
          type: string
          format: uri
      required:
      - background_image
      - business_nature
      - company_address
      - company_email
      - company_information
      - company_name
      - confirm_password
      - password
      - profile_picture
    Department:
      type: object
      properties:
        department_id:
          type: integer
          readOnly: true
        department_name:
          type: string
          maxLength: 100
      required:
      - department_id
      - department_name
    DepartmentNested:
      type: object
      properties:
        department_id:
          type: integer
          readOnly: true
        department_name:
          type: string
          readOnly: true
        programs:
          type: array
          items:
            $ref: '#/components/schemas/ProgramNested'
          readOnly: true
      required:
      - department_id
      - department_name
      - programs
    MyTokenObtainPair:
      type: object
      properties:
        email:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
      required:
      - email
      - password
    NestedSchoolDepartmentProgram:
      type: object
      properties:
        school_id:
          type: string
          format: uuid
          readOnly: true
        school_name:
          type: string
          readOnly: true
        departments:
          type: array
          items:
            $ref: '#/components/schemas/DepartmentNested'
          readOnly: true
      required:
      - departments
      - school_id
      - school_name
    OJTCoordinatorRegister:
      type: object
      properties:
        OJTCoordinator_email:
          type: string
          format: email
          writeOnly: true
        first_name:
          type: string
          maxLength: 100
        last_name:
          type: string
          maxLength: 100
        middle_initial:
          type: string
          writeOnly: true
          default: ''
        password:
          type: string
          writeOnly: true
        confirm_password:
          type: string
          writeOnly: true
        program:
          type: integer
      required:
      - OJTCoordinator_email
      - confirm_password
      - first_name
      - last_name
      - password
      - program
    ProgramNested:
      type: object
      properties:
        program_id:
          type: integer
          readOnly: true
        program_name:
          type: string
          readOnly: true
      required:
      - program_id
      - program_name
    School:
      type: object
      properties:
        school_id:
          type: string
          format: uuid
          readOnly: true
        school_name:
          type: string
          maxLength: 255
      required:
      - school_id
      - school_name
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
