# Generated by Django 5.2 on 2025-04-16 09:11

import storages.backends.s3
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advertisement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.FileField(storage=storages.backends.s3.S3Storage, upload_to='')),
                ('redirect_url', models.CharField(blank=True, max_length=255, null=True)),
                ('caption_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('benefit_id', models.AutoField(primary_key=True, serialize=False)),
                ('benefits', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardSkillsTagList',
            fields=[
                ('hard_skills_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('lightcast_identifier', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipPosting',
            fields=[
                ('internship_posting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internship_position', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('other_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('is_paid_internship', models.BooleanField(default=False)),
                ('is_only_for_practicum', models.BooleanField(default=False)),
                ('internship_date_start', models.DateTimeField()),
                ('ojt_hours', models.IntegerField()),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Expired', 'Expired')], default='Open', max_length=20)),
                ('modality', models.CharField(choices=[('Onsite', 'Onsite'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], default='Onsite', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipRecommendation',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('similarity_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Viewed', 'Viewed'), ('Submitted', 'Submitted'), ('Skipped', 'Skipped')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KeyTask',
            fields=[
                ('key_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_tasks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MinQualification',
            fields=[
                ('min_qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_qualifications', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonInCharge',
            fields=[
                ('person_in_charge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('landline_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'PIC',
                'verbose_name_plural': 'PICs',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Solved', 'Solved'), ('Deleted', 'Deleted')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RequiredHardSkill',
            fields=[
                ('required_hard_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lightcast_identifier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RequiredSoftSkill',
            fields=[
                ('required_soft_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lightcast_identifier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkillsTagList',
            fields=[
                ('soft_skills_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('lightcast_identifier', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
