# Generated by Django 5.2 on 2025-04-16 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_matching', '0001_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardskillstaglist',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.applicant'),
        ),
        migrations.AddField(
            model_name='internshipposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.company'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='internship_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_matching.internshipposting'),
        ),
        migrations.AddField(
            model_name='internshiprecommendation',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.applicant'),
        ),
        migrations.AddField(
            model_name='internshiprecommendation',
            name='internship_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_matching.internshipposting'),
        ),
        migrations.AddField(
            model_name='keytask',
            name='internship_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_matching.internshipposting'),
        ),
        migrations.AddField(
            model_name='minqualification',
            name='internship_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_matching.internshipposting'),
        ),
        migrations.AddField(
            model_name='personincharge',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.company'),
        ),
        migrations.AddField(
            model_name='internshipposting',
            name='person_in_charge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client_matching.personincharge'),
        ),
        migrations.AddField(
            model_name='report',
            name='internship_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_matching.internshipposting'),
        ),
        migrations.AddField(
            model_name='requiredhardskill',
            name='internship_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_matching.internshipposting'),
        ),
        migrations.AddField(
            model_name='requiredsoftskill',
            name='internship_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_matching.internshipposting'),
        ),
        migrations.AddField(
            model_name='softskillstaglist',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.applicant'),
        ),
        migrations.AlterUniqueTogether(
            name='hardskillstaglist',
            unique_together={('applicant', 'lightcast_identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='requiredhardskill',
            unique_together={('internship_posting', 'lightcast_identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='requiredsoftskill',
            unique_together={('internship_posting', 'lightcast_identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='softskillstaglist',
            unique_together={('applicant', 'lightcast_identifier')},
        ),
    ]
