# Generated by Django 5.2 on 2025-06-23 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_matching', '0001_initial'),
        ('user_account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.company'),
        ),
        migrations.AddField(
            model_name='internshipposting',
            name='required_hard_skills',
            field=models.ManyToManyField(blank=True, related_name='required_hard_skills', to='client_matching.hardskillstaglist'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='internship_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='client_matching.internshipposting'),
        ),
        migrations.AddField(
            model_name='internshiprecommendation',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.applicant'),
        ),
        migrations.AddField(
            model_name='internshiprecommendation',
            name='internship_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_matching.internshipposting'),
        ),
        migrations.AddField(
            model_name='keytask',
            name='internship_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_tasks', to='client_matching.internshipposting'),
        ),
        migrations.AddField(
            model_name='minqualification',
            name='internship_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_qualifications', to='client_matching.internshipposting'),
        ),
        migrations.AddField(
            model_name='personincharge',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.company'),
        ),
        migrations.AddField(
            model_name='internshipposting',
            name='person_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_matching.personincharge'),
        ),
        migrations.AddField(
            model_name='report',
            name='internship_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_matching.internshipposting'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internshipposting',
            name='required_soft_skills',
            field=models.ManyToManyField(blank=True, related_name='required_soft_skills', to='client_matching.softskillstaglist'),
        ),
    ]
