# Generated by Django 5.2 on 2025-06-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_matching', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipposting',
            name='ojt_hours',
            field=models.PositiveIntegerField(),
        ),
    ]
