# Generated by Django 5.2 on 2025-06-30 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_matching', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipposting',
            name='person_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_matching.personincharge'),
        ),
    ]
