# Generated by Django 5.2 on 2025-07-04 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_matching', '0003_alter_internshipposting_person_in_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipposting',
            name='person_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client_matching.personincharge'),
        ),
    ]
