# Generated by Django 5.2 on 2025-06-07 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_matching', '0004_alter_internshipposting_ojt_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipposting',
            name='ojt_hours',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
