# Generated by Django 5.2 on 2025-07-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_matching', '0004_alter_internshipposting_person_in_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipposting',
            name='accepted_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internshipposting',
            name='max_slots',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
