# Generated by Django 5.2 on 2025-06-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_matching', '0005_alter_internshipposting_ojt_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipposting',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='internshipposting',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
