# Generated by Django 5.2 on 2025-07-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_matching', '0005_internshipposting_accepted_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipposting',
            name='accepted_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
