# Generated by Django 5.2 on 2025-07-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_matching', '0006_alter_internshipposting_accepted_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipposting',
            name='max_slots',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
