# Generated by Django 5.2 on 2025-09-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_matching', '0007_alter_internshipposting_max_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipposting',
            name='accepted_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internshipposting',
            name='max_slots',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
