# Generated by Django 5.2 on 2025-06-01 05:50

import django.core.validators
import django.db.models.deletion
import storages.backends.s3
import user_account.filepaths
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cea_management', '0001_initial'),
        ('client_matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deleted', 'Deleted'), ('Pending', 'Pending'), ('Suspended', 'Suspended')], default='Pending', max_length=20)),
                ('user_role', models.CharField(choices=[('admin', 'admin'), ('applicant', 'applicant'), ('company', 'company'), ('cea', 'cea'), ('coordinator', 'coordinator')], default='admin', max_length=20)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=255)),
                ('in_practicum', models.CharField(choices=[('No', 'No'), ('Pending', 'Pending'), ('Yes', 'Yes')], default='No', max_length=20)),
                ('preferred_modality', models.CharField(choices=[('Onsite', 'Onsite'), ('WorkFromHome', 'WorkFromHome'), ('Hybrid', 'Hybrid')], default='Onsite', max_length=20)),
                ('academic_program', models.CharField(blank=True, max_length=100, null=True)),
                ('quick_introduction', models.CharField(max_length=500)),
                ('resume', models.FileField(storage=storages.backends.s3.S3Storage, upload_to=user_account.filepaths.applicant_resume)),
                ('enrollment_record', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage, upload_to=user_account.filepaths.applicant_enrollment_record)),
                ('last_matched', models.DateTimeField(blank=True, null=True)),
                ('last_recommendation_filter_state', models.JSONField(blank=True, null=True)),
                ('tap_count_reset', models.DateTimeField(blank=True, null=True)),
                ('tap_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cea_management.department')),
                ('hard_skills', models.ManyToManyField(blank=True, related_name='applicant_hard_skills', to='client_matching.hardskillstaglist')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cea_management.program')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cea_management.school')),
                ('soft_skills', models.ManyToManyField(blank=True, related_name='applicant_soft_skills', to='client_matching.softskillstaglist')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerEmplacementAdmin',
            fields=[
                ('cea_id', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cea_management.school')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CEA',
                'verbose_name_plural': 'CEAs',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('company_information', models.CharField(max_length=500)),
                ('business_nature', models.CharField(max_length=100)),
                ('company_website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=255, null=True)),
                ('x_url', models.CharField(blank=True, max_length=255, null=True)),
                ('other_url', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.FileField(storage=storages.backends.s3.S3Storage, upload_to=user_account.filepaths.company_background_image)),
                ('profile_picture', models.FileField(storage=storages.backends.s3.S3Storage, upload_to=user_account.filepaths.company_profile_picture)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='OJTCoordinator',
            fields=[
                ('ojt_coordinator_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=20, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cea_management.program')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OJT Coordinator',
                'verbose_name_plural': 'OJT Coordinators',
            },
        ),
    ]
