# Generated by Django 5.2 on 2025-06-02 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cea_management', '0002_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojtcoordinator',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cea_management.program'),
        ),
    ]
