# Generated by Django 5.2 on 2025-04-17 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cea_management', '0003_alter_department_school_alter_program_department'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cea_management.department'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_account.school'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
