# Generated by Django 5.2 on 2025-04-18 13:41

import storages.backends.s3
import user_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_applicant_department_applicant_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='enrollment_record',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage, upload_to=user_account.models.applicant_enrollment_record_upload_path),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(storage=storages.backends.s3.S3Storage, upload_to=user_account.models.applicant_resume_upload_path),
        ),
    ]
