# Generated by Django 5.2 on 2025-06-02 07:54

import storages.backends.s3
import user_account.filepaths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_ojtcoordinator_program_logo_ojtcoordinator_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojtcoordinator',
            name='program_logo',
            field=models.FileField(storage=storages.backends.s3.S3Storage, upload_to=user_account.filepaths.coordinator_program_logo),
        ),
        migrations.AlterField(
            model_name='ojtcoordinator',
            name='signature',
            field=models.FileField(storage=storages.backends.s3.S3Storage, upload_to=user_account.filepaths.coordinator_signature),
        ),
    ]
