# Generated by Django 5.2 on 2025-06-03 08:55

import storages.backends.s3
import user_account.filepaths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_alter_ojtcoordinator_program_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(default='', storage=storages.backends.s3.S3Storage, upload_to=user_account.filepaths.applicant_resume),
        ),
        migrations.AlterField(
            model_name='ojtcoordinator',
            name='program_logo',
            field=models.FileField(default='', storage=storages.backends.s3.S3Storage, upload_to=user_account.filepaths.coordinator_program_logo),
        ),
        migrations.AlterField(
            model_name='ojtcoordinator',
            name='signature',
            field=models.FileField(default='', storage=storages.backends.s3.S3Storage, upload_to=user_account.filepaths.coordinator_signature),
        ),
    ]
