# Generated by Django 5.2 on 2025-06-04 08:29

import storages.backends.s3
import user_account.filepaths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_alter_applicant_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojtcoordinator',
            name='program_logo',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage, upload_to=user_account.filepaths.coordinator_program_logo),
        ),
        migrations.AlterField(
            model_name='ojtcoordinator',
            name='signature',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage, upload_to=user_account.filepaths.coordinator_signature),
        ),
    ]
