# Generated by Django 5.2 on 2025-06-07 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cea_management', '0002_initial'),
        ('user_account', '0006_alter_ojtcoordinator_program_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ojtcoordinator',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cea_management.department'),
        ),
    ]
