# Generated by Django 5.2 on 2025-06-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_applicant_mobile_number_ojtcoordinator_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
