# Generated by Django 5.2 on 2025-06-09 07:01

import django.db.models.deletion
import storages.backends.s3
import user_account.filepaths
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_alter_applicant_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(storage=storages.backends.s3.S3Storage, upload_to=user_account.filepaths.applicant_resume),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('auditlog_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role', models.CharField(choices=[('admin', 'admin'), ('applicant', 'applicant'), ('company', 'company'), ('cea', 'cea'), ('coordinator', 'coordinator')], default='admin', max_length=20)),
                ('action', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=50)),
                ('object_repr', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
