# Generated by Django 5.2 on 2025-06-09 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cea_management', '0002_initial'),
        ('user_account', '0009_alter_applicant_resume_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ojtcoordinator',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cea_management.department'),
        ),
    ]
