# Generated by Django 5.2 on 2025-06-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_alter_applicant_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('add', 'add'), ('change', 'change'), ('delete', 'delete')], default='', max_length=10),
        ),
    ]
