# Generated by Django 5.2 on 2025-06-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0011_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('add', 'add'), ('change', 'change'), ('delete', 'delete')], max_length=10),
        ),
    ]
