# Generated by Django 5.2 on 2025-06-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(blank=True, choices=[('add', 'add'), ('change', 'change'), ('delete', 'delete')], max_length=10, null=True),
        ),
    ]
