# Generated by Django 5.2 on 2025-06-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0013_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtcoordinator',
            name='endorsements_responded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
