# Generated by Django 5.2 on 2025-06-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0014_ojtcoordinator_endorsements_responded'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='applicant',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
