# Generated by Django 5.2 on 2025-06-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0015_applicant_latitude_applicant_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='company',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='company',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
