# Generated by Django 5.2 on 2025-06-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0016_alter_applicant_latitude_alter_applicant_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='company',
            name='longitude',
        ),
    ]
