# Generated by Django 5.2 on 2025-06-01 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cea_management', '0001_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpartnershiplist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.company'),
        ),
        migrations.AddField(
            model_name='schoolpartnershiplist',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cea_management.school'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('department', 'program_name')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('school', 'department_name')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolpartnershiplist',
            unique_together={('school', 'company')},
        ),
    ]
