# Generated by Django 5.2 on 2025-04-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cea_management', '0003_alter_department_school_alter_program_department'),
        ('user_account', '0003_alter_applicant_enrollment_record_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='name',
            new_name='program_name',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('school', 'department_name')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('department', 'program_name')},
        ),
    ]
