# Generated by Django 5.2 on 2025-06-23 12:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Onboarding', 'Onboarding'), ('Rejected', 'Rejected'), ('Dropped', 'Dropped'), ('Accepted', 'Accepted')], default='Pending', max_length=20)),
                ('is_bookmarked', models.BooleanField(default=True)),
                ('applicant_status', models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread'), ('Deleted', 'Deleted')], default='Unread', max_length=20)),
                ('company_status', models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread'), ('Deleted', 'Deleted')], default='Unread', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('endorsement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deleted', 'Deleted')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_text', models.CharField(max_length=300)),
                ('notification_type', models.CharField(choices=[('Applicant', 'Applicant'), ('Company', 'Company')], max_length=20)),
            ],
        ),
    ]
