# Generated by Django 5.2 on 2025-04-16 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_application', '0001_initial'),
        ('client_matching', '0001_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.applicant'),
        ),
        migrations.AddField(
            model_name='application',
            name='internship_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_matching.internshipposting'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_application.application'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='ojt_coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.ojtcoordinator'),
        ),
        migrations.AddField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_application.application'),
        ),
    ]
