# Generated by Django 5.2 on 2025-06-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client_application.application'),
        ),
    ]
