# Generated by Django 5.2 on 2025-07-25 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_application', '0002_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user_account.applicant'),
        ),
    ]
