# Generated by Django 5.2 on 2025-06-03 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_application', '0003_alter_endorsement_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_application.application'),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deleted', 'Deleted')], default='Pending', max_length=20),
        ),
    ]
