# Generated by Django 5.2 on 2025-06-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_application', '0004_alter_endorsement_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Onboarding', 'Onboarding'), ('Rejected', 'Rejected'), ('Dropped', 'Dropped'), ('Accepted', 'Accepted')], default='Pending', max_length=20),
        ),
    ]
